export const counterActions = {
  DECREMENT_COUNT: "DECREMENT_COUNT",
  INCREMENT_COUNT: "INCREMENT_COUNT",
  ZERO_COUNT: "ZERO_COUNT",
};

export const dateTimeActions = {
  DECREMENT_DAY: "DECREMENT_DAY",
  DECREMENT_HOUR: "DECREMENT_HOUR",
  DECREMENT_WEEK: "DECREMENT_WEEK",
  INCREMENT_DAY: "INCREMENT_DAY",
  INCREMENT_HOUR: "INCREMENT_HOUR",
  INCREMENT_WEEK: "INCREMENT_WEEK",
  RESET_DATETIME_TO_NOW: "RESET_DATETIME_TO_NOW",
};

export const saveNameActions = {
  SAVE_NAME: "SAVE_NAME"
}

export const saveNameLegacyActions = {
  SAVE_NAME_LEGACY: "SAVE_NAME_LEGACY"
}